import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { AppShell } from '@/components/AppShell';
import { Toaster } from "@/components/ui/toaster";
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'MindSafe Med',
  description: 'Your personal health tracking assistant.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn(
          'min-h-screen bg-background font-body antialiased',
        )}
      >
        <div className="flex flex-col min-h-screen">
          <AppShell>{children}</AppShell>
          <Toaster />
          <footer className="p-6 mt-auto border-t bg-muted/40">
             <div className="max-w-2xl mx-auto space-y-3 text-center text-xs text-muted-foreground">
                <p className="font-semibold text-base text-foreground">Disclaimer: This is Not Medical Advice</p>
                <p>
                  MindSafe Med is an informational and educational tool designed to help you organize your health information. It is not a substitute for professional medical advice, diagnosis, or treatment. The information and summaries generated by this application are for educational purposes only and should not be considered a medical diagnosis.
                </p>
                <p>
                  <strong>Always seek the advice of your physician or another qualified health provider</strong> with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read or seen on this application.
                </p>
                <p className="pt-2">
                  <Link href="/privacy" className="underline hover:text-foreground">
                    Privacy Policy
                  </Link>
                </p>
              </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
